import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { SalesRecord } from "@/lib/api";
import { sarabunRegularBase64 } from "@/lib/fonts/sarabun-regular";

// Converted from the site's actual OKLCH theme tokens (app/globals.css)
// so the PDF matches the web app's brand color exactly.
const BRAND = "#2958cb"; // --primary: oklch(0.5 0.185 264)
const BRAND_TINT = "#e1ebff"; // --accent: oklch(0.94 0.03 265)
const BRAND_TEXT_ON_TINT = "#172f65"; // --accent-foreground: oklch(0.32 0.1 265)
const INK = "#0f141d"; // --foreground: oklch(0.19 0.02 265)
const MUTED = "#5e636f"; // --muted-foreground: oklch(0.5 0.02 265)
const SURFACE = "#eff2f6"; // --muted: oklch(0.96 0.006 260)

const MARGIN = 14;

function number(value: number) {
  return value.toLocaleString(undefined, { maximumFractionDigits: 0 });
}

export function exportSalesReportPdf(records: SalesRecord[], insight: string | null) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN * 2;

  doc.addFileToVFS("Sarabun-Regular.ttf", sarabunRegularBase64);
  doc.addFont("Sarabun-Regular.ttf", "Sarabun", "normal");
  doc.setFont("Sarabun");

  // Header band
  doc.setFillColor(BRAND);
  doc.rect(0, 0, pageWidth, 26, "F");

  doc.setTextColor("#ffffff");
  doc.setFontSize(15);
  doc.text("Teamsight", MARGIN, 12);
  doc.setFontSize(9.5);
  doc.setTextColor("#e0e7ff");
  doc.text("Sales Report", MARGIN, 19);

  const generatedAt = new Date().toLocaleString();
  doc.setFontSize(9);
  doc.setTextColor("#e0e7ff");
  doc.text(`Generated ${generatedAt}`, pageWidth - MARGIN, 19, { align: "right" });

  let cursorY = 38;

  // KPI summary boxes
  const totalRevenue = records.reduce((sum, r) => sum + Number(r.amount), 0);
  const recordCount = records.length;
  const avgDeal = recordCount === 0 ? 0 : totalRevenue / recordCount;

  const kpis = [
    { label: "Total revenue", value: number(totalRevenue) + " THB" },
    { label: "Records", value: String(recordCount) },
    { label: "Avg. deal size", value: number(avgDeal) + " THB" },
  ];

  const gap = 6;
  const boxWidth = (contentWidth - gap * (kpis.length - 1)) / kpis.length;
  const boxHeight = 20;

  kpis.forEach((kpi, i) => {
    const x = MARGIN + i * (boxWidth + gap);
    doc.setFillColor(SURFACE);
    doc.roundedRect(x, cursorY, boxWidth, boxHeight, 2, 2, "F");

    doc.setFontSize(8.5);
    doc.setTextColor(MUTED);
    doc.text(kpi.label, x + 5, cursorY + 8);

    doc.setFontSize(13);
    doc.setTextColor(INK);
    doc.text(kpi.value, x + 5, cursorY + 16);
  });

  cursorY += boxHeight + 12;

  // AI insight block
  if (insight) {
    doc.setFontSize(10.5);
    doc.setTextColor(BRAND_TEXT_ON_TINT);
    doc.text("AI Insight", MARGIN, cursorY);
    cursorY += 5;

    doc.setFontSize(10);
    const innerPadding = 5;
    const lines = doc.splitTextToSize(insight, contentWidth - innerPadding * 2);
    const boxHeightInsight = lines.length * 5 + innerPadding * 2;

    doc.setFillColor(BRAND_TINT);
    doc.roundedRect(MARGIN, cursorY, contentWidth, boxHeightInsight, 2, 2, "F");

    doc.setTextColor(INK);
    doc.text(lines, MARGIN + innerPadding, cursorY + innerPadding + 3.5);

    cursorY += boxHeightInsight + 10;
  }

  autoTable(doc, {
    startY: cursorY,
    margin: { left: MARGIN, right: MARGIN },
    styles: { font: "Sarabun", fontSize: 9.5, textColor: INK },
    headStyles: { fillColor: BRAND, textColor: "#ffffff", fontStyle: "normal" },
    alternateRowStyles: { fillColor: SURFACE },
    columnStyles: {
      1: { halign: "right" },
    },
    head: [["Product", "Amount", "Team", "Sold At", "Recorded By"]],
    body: records.map((r) => [
      r.product,
      number(Number(r.amount)) + " THB",
      r.team.name,
      new Date(r.soldAt).toLocaleDateString(),
      r.recordedBy.name,
    ]),
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setDrawColor(SURFACE);
      doc.line(MARGIN, pageHeight - 14, pageWidth - MARGIN, pageHeight - 14);

      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text("Generated by Teamsight", MARGIN, pageHeight - 8);
      doc.text(`Page ${data.pageNumber}`, pageWidth - MARGIN, pageHeight - 8, {
        align: "right",
      });
    },
  });

  doc.save(`teamsight-sales-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
